name: Slicing

on:
  push:
    paths:
    - '**.stl'
    - '**.amf'
    - '**.STL'
    - '**.AMF'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Slicovani 3D
        uses: roman-dvorak/Slice@master
        with:
          printer: "3d" 
      - name: Slicovani mlab
        uses: roman-dvorak/Slice@master
        with:
          printer: "mlab"
      - name: Upload
        uses: crykn/copy_folder_to_another_repo_action@v1.0.5
        continue-on-error: true
        with:
          source_folder: 'out'
          destination_repo: 'roman-dvorak/for_printing'
          destination_branch: 'master'
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.7
        with:
          # Artifact name
          name: "out"
          # Destination path
          path: "out"  
      
#       uses: crykn/copy_folder_to_another_repo_action@v1.0.5
