name: Slicing

on:
  push:
    paths:
    - '**.stl'
    - '**.amf'
    - '**.STL'
    - '**.AMF'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        printer: ['3d', 'mlab']
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout output
        uses: actions/checkout@v2
        with:
          repository: roman-dvorak/for_printing
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: 'for_printing'

      - name: Slicovani pro ${{ matrix.printer }}
        uses: roman-dvorak/Slice@master
        with:
          printer: ${{ matrix.printer }}

      - name: Upload
        uses: plocket/push-generated-file@master
        continue-on-error: true
        with:
          source_file_path: 'out'
          destination_repo: 'roman-dvorak/for_printing'
          target_branch:  ${${{github.head_ref}}##*/}/${{ matrix.printer }}
          token: ${{ secrets.API_TOKEN_GITHUB }}
      
      - name: Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: "out"
          path: "."  
      
#       uses: crykn/copy_folder_to_another_repo_action@v1.0.5
