name: Slicing

on:
  push:
    paths:
    - '**.stl'
    - '**.amf'
    - '**.STL'
    - '**.AMF'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Slicovani 3D
        uses: roman-dvorak/Slice@master
        with:
          printer: "3d" 
      - name: Slicovani mlab
        uses: roman-dvorak/Slice@master
        with:
          printer: "mlab"
