name: Slicing

on:
  push:
    paths:
    - '**.stl'
    - '**.amf'
    - '**.STL'
    - '**.AMF'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        printer: ['3d', 'mlab']
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout output
        uses: actions/checkout@v2
        with:
          repository: roman-dvorak/for_printing
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: 'for_printing'

      - name: Slicovani pro ${{ matrix.printer }}
        uses: roman-dvorak/Slice@master
        with:
          printer: ${{ matrix.printer }}

      - name: Upload
        uses: cpina/github-action-push-to-another-repository@v1.2
        continue-on-error: true
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'out'
          destination-github-username: 'roman-dvorak'
          destination-repository-name: 'for_printing'

      - name: Upload2
        uses: cpina/github-action-push-to-another-repository@v1.2
        continue-on-error: true
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'out'
          destination-github-username: 'roman-dvorak'
          destination-repository-name: 'for_printing'
          target-branch:  ${{ github.repository }}
        
      - name: push3
        uses: crykn/copy_folder_to_another_repo_action@v1.0.5b
        continue-on-error: true
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'out'
          destination_repo: 'roman-dvorak/for_printing'
          destination_branch: ${{ github.head_ref }}      
      
      - name: Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: "out"
          path: "."  
      
#       uses: crykn/copy_folder_to_another_repo_action@v1.0.5
